# doctrine_migrations:
#     migrations_paths:
#         # namespace is arbitrary but should be different from App\Migrations
#         # as migrations classes should NOT be autoloaded
#         'DoctrineMigrations': '%kernel.project_dir%/migrations'
doctrine_migrations:
    dir_name: '%kernel.project_dir%/migrations'
    namespace: 'DoctrineMigrations'
    table_name: 'doctrine_migration_versions'
    default_column_options:
        type: string
        length: 255
    all_or_nothing: true
    check_database_platform: true
