<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '34c6873ff51f1df3dc7dcaa98ba6f8a9',
  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/reflet?serverVersion=5.7',
  'LOCK_DSN' => 'semaphore',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
  'JWT_SECRET_KEY' => '%kernel.project_dir%/config/jwt/private.pem',
  'JWT_PUBLIC_KEY' => '%kernel.project_dir%/config/jwt/public.pem',
  'JWT_PASSPHRASE' => '8d91ad16944e9261c38a835177b6113c',
);
